{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6b6f88b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting Django\n",
      "  Downloading Django-4.1.3-py3-none-any.whl (8.1 MB)\n",
      "     ---------------------------------------- 8.1/8.1 MB 24.6 MB/s eta 0:00:00\n",
      "Collecting djangorestframework\n",
      "  Using cached djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)\n",
      "Collecting sqlparse>=0.2.2\n",
      "  Using cached sqlparse-0.4.3-py3-none-any.whl (42 kB)\n",
      "Collecting asgiref<4,>=3.5.2\n",
      "  Using cached asgiref-3.5.2-py3-none-any.whl (22 kB)\n",
      "Collecting tzdata\n",
      "  Downloading tzdata-2022.6-py2.py3-none-any.whl (338 kB)\n",
      "     ---------------------------------------- 338.8/338.8 kB ? eta 0:00:00\n",
      "Requirement already satisfied: pytz in c:\\users\\matteolai\\anaconda3\\lib\\site-packages (from djangorestframework) (2022.1)\n",
      "Installing collected packages: tzdata, sqlparse, asgiref, Django, djangorestframework\n",
      "Successfully installed Django-4.1.3 asgiref-3.5.2 djangorestframework-3.14.0 sqlparse-0.4.3 tzdata-2022.6\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install Django djangorestframework"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "427f79e8",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (2573179797.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"C:\\Users\\matteolai\\AppData\\Local\\Temp\\ipykernel_10412\\2573179797.py\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    django-admin startproject countryapi\u001b[0m\n\u001b[1;37m                 ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "django-admin startproject countryapi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "73d949c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "Microsoft Windows [Version 10.0.19045.2251]\n",
    "(c) Microsoft Corporation. All rights reserved.\n",
    "\n",
    "C:\\Users\\matteolai> cd \\Users\\matteolai\\flask_matteo\\venv\\venv\\\n",
    "\n",
    "C:\\Users\\matteolai\\flask_matteo\\venv\\venv> python cracovia.py\n",
    "\n",
    "C:\\Users\\matteolai\\flask_matteo\\venv\\venv>python run cracovia.py\n",
    "python: can't open file 'C:\\Users\\matteolai\\flask_matteo\\venv\\venv\\run': [Errno 2] No such file or directory\n",
    "\n",
    "C:\\Users\\matteolai\\flask_matteo\\venv\\venv> cd \\Users\\matteolai\\django_project\\\n",
    "\n",
    "C:\\Users\\matteolai\\django_project>py -m venv env\n",
    "\n",
    "C:\\Users\\matteolai\\django_project>.\\env\\Scripts\\activate\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project>pip install Django djangorestframework\n",
    "Collecting Django\n",
    "  Using cached Django-4.1.3-py3-none-any.whl (8.1 MB)\n",
    "Collecting djangorestframework\n",
    "  Using cached djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)\n",
    "Collecting asgiref<4,>=3.5.2\n",
    "  Using cached asgiref-3.5.2-py3-none-any.whl (22 kB)\n",
    "Collecting tzdata\n",
    "  Using cached tzdata-2022.6-py2.py3-none-any.whl (338 kB)\n",
    "Collecting sqlparse>=0.2.2\n",
    "  Using cached sqlparse-0.4.3-py3-none-any.whl (42 kB)\n",
    "Collecting pytz\n",
    "  Using cached pytz-2022.6-py2.py3-none-any.whl (498 kB)\n",
    "Installing collected packages: pytz, tzdata, sqlparse, asgiref, Django, djangorestframework\n",
    "Successfully installed Django-4.1.3 asgiref-3.5.2 djangorestframework-3.14.0 pytz-2022.6 sqlparse-0.4.3 tzdata-2022.6\n",
    "\n",
    "[notice] A new release of pip available: 22.2.2 -> 22.3.1\n",
    "[notice] To update, run: python.exe -m pip install --upgrade pip\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project>django-admin startproject countryapi\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project> cd \\Users\\matteolai\\django_project\\countryapi\\\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi> python manage.py startapp countries\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi> python manage.py makemigrations\n",
    "Migrations for 'countries':\n",
    "  countries\\migrations\\0001_initial.py\n",
    "    - Create model Country\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py migrate\n",
    "Operations to perform:\n",
    "  Apply all migrations: admin, auth, contenttypes, countries, sessions\n",
    "Running migrations:\n",
    "  Applying contenttypes.0001_initial... OK\n",
    "  Applying auth.0001_initial... OK\n",
    "  Applying admin.0001_initial... OK\n",
    "  Applying admin.0002_logentry_remove_auto_add... OK\n",
    "  Applying admin.0003_logentry_add_action_flag_choices... OK\n",
    "  Applying contenttypes.0002_remove_content_type_name... OK\n",
    "  Applying auth.0002_alter_permission_name_max_length... OK\n",
    "  Applying auth.0003_alter_user_email_max_length... OK\n",
    "  Applying auth.0004_alter_user_username_opts... OK\n",
    "  Applying auth.0005_alter_user_last_login_null... OK\n",
    "  Applying auth.0006_require_contenttypes_0002... OK\n",
    "  Applying auth.0007_alter_validators_add_error_messages... OK\n",
    "  Applying auth.0008_alter_user_username_max_length... OK\n",
    "  Applying auth.0009_alter_user_last_name_max_length... OK\n",
    "  Applying auth.0010_alter_group_name_max_length... OK\n",
    "  Applying auth.0011_update_proxy_permissions... OK\n",
    "  Applying auth.0012_alter_user_first_name_max_length... OK\n",
    "  Applying countries.0001_initial... OK\n",
    "  Applying sessions.0001_initial... OK\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py loaddata countries.json\n",
    "CommandError: No fixture named 'countries' found.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi> cd \\countries\\\n",
    "The system cannot find the path specified.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi> cd \\Users\\matteolai\\django_project\\countryapi\\countries\\\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi\\countries>python manage.py loaddata countries.json\n",
    "C:\\Users\\matteolai\\AppData\\Local\\Programs\\Python\\Python310\\python.exe: can't open file 'C:\\\\Users\\\\matteolai\\\\django_project\\\\countryapi\\\\countries\\\\manage.py': [Errno 2] No such file or directory\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi\\countries>python manage.py loaddata countries.json\n",
    "C:\\Users\\matteolai\\AppData\\Local\\Programs\\Python\\Python310\\python.exe: can't open file 'C:\\\\Users\\\\matteolai\\\\django_project\\\\countryapi\\\\countries\\\\manage.py': [Errno 2] No such file or directory\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi\\countries> cd \\Users\\matteolai\\django_project\\countryapi\\\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py loaddata countries.json\n",
    "CommandError: No fixture named 'countries' found.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py django_project/countryapi/countries.json\n",
    "Unknown command: 'django_project/countryapi/countries.json'\n",
    "Type 'manage.py help' for usage.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>manage.py help\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py loaddata 'countries.json'\n",
    "CommandError: Problem installing fixture ''countries': json' is not a known serialization format.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py loaddata <countries>.json\n",
    "Access is denied.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py loaddata <countries>.json\n",
    "Access is denied.\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py loaddata --countries.json\n",
    "usage: manage.py loaddata [-h] [--database DATABASE] [--app APP_LABEL] [--ignorenonexistent] [-e EXCLUDE]\n",
    "                          [--format FORMAT] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH]\n",
    "                          [--traceback] [--no-color] [--force-color] [--skip-checks]\n",
    "                          fixture [fixture ...]\n",
    "manage.py loaddata: error: the following arguments are required: fixture\n",
    "\n",
    "(env) C:\\Users\\matteolai\\django_project\\countryapi>python manage.py runserver\n",
    "Watching for file changes with StatReloader\n",
    "Performing system checks...\n",
    "\n",
    "System check identified no issues (0 silenced).\n",
    "November 23, 2022 - 17:50:53\n",
    "Django version 4.1.3, using settings 'countryapi.settings'\n",
    "Starting development server at http://127.0.0.1:8000/\n",
    "Quit the server with CTRL-BREAK.\n",
    "[23/Nov/2022 17:51:07] \"GET / HTTP/1.1\" 200 10681\n",
    "[23/Nov/2022 17:51:07] \"GET /static/admin/css/fonts.css HTTP/1.1\" 200 423\n",
    "[23/Nov/2022 17:51:07] \"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 200 85876\n",
    "[23/Nov/2022 17:51:07] \"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 200 86184\n",
    "[23/Nov/2022 17:51:07] \"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 200 85692\n",
    "Not Found: /favicon.ico\n",
    "[23/Nov/2022 17:51:07] \"GET /favicon.ico HTTP/1.1\" 404 2114"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
